import numpy as np
import pybamm

class PybammPropagator:
    """
    Propagate a numerical PyBaMM state through one complete experiment.

        (t_n, u_n) -> (t_{n+1}, u_{n+1}).
    """

    def __init__(
        self,
        model,
        experiment,
        parameter_values,
        var_pts,
        solver=None,
        inputs=None,
        experiment_model_mode="legacy",
    ):
        self.inputs = {} if inputs is None else dict(inputs)

        self.solver = solver or pybamm.IDAKLUSolver()

        self.sim = pybamm.Simulation(
            model,
            experiment=experiment,
            parameter_values=parameter_values,
            solver=self.solver,
            var_pts=var_pts,
            experiment_model_mode=experiment_model_mode,
        )

        # Parameterise, mesh and discretise the experiment models once.
        self.sim.build_for_experiment(inputs=self.inputs)

        # The PinT interface is located after the final experiment step.
        self.interface_step = self.sim.experiment.steps[-1]

        # Current PyBaMM provides this internal helper to select either
        # the unified model or the appropriate legacy step model.
        self.interface_model = self.sim._get_built_experiment_model(
            self.interface_step
        )

        # Dimension of the complete differential + algebraic state.
        self.state_size = self.interface_model.len_rhs_and_alg

    def make_state(self, t, u):
        """
        Construct a one-state PyBaMM Solution from a PinT interface state.

        Parameters
        ----------
        t : float
            Absolute numerical simulation time [s].
        u : array-like
            Complete discretised PyBaMM DAE state.

        Returns
        -------
        pybamm.Solution
            One-state Solution suitable for use as starting_solution.
        """
        t = t
        u = np.asarray(u).reshape(-1)

        if u.size != self.state_size:
            raise ValueError(
                "Interface-state size mismatch: "
                f"received {u.size}, expected {self.state_size}."
            )

        # This Solution acts only as a restart container. Experiment-step
        # inputs for the new propagation are generated by Simulation.solve.
        state = pybamm.Solution(
            all_ts=t,
            all_ys=u,
            all_models=self.interface_model,
            all_inputs=self.inputs,
            termination="final time",
        )

        # Relevant only for experiments using calendar start_time.
        state.initial_start_time = self.sim.experiment.initial_start_time

        return state

    def extract_state(self, solution):
        """
        Extract the numerical PinT interface state from a PyBaMM Solution.

        Parameters
        ----------
        solution : pybamm.Solution
            Solution whose final state is the experiment interface.

        Returns
        -------
        t : float
            Interface time [s].
        u : numpy.ndarray
            Complete discretised DAE state.
        """
        state = solution.last_state

        t = state.t[-1]
        u = np.asarray(state.y).reshape(-1).copy()

        if u.size != self.state_size:
            raise ValueError(
                "Returned interface-state size mismatch: "
                f"received {u.size}, expected {self.state_size}."
            )

        return t, u

    def propagate(self, starting_state):
        """
        Propagate one complete experiment from (t, u).

        Parameters
        ----------
        t : float
            Starting numerical time [s].
        u : array-like
            Starting complete DAE state.

        Returns
        -------
        t_next : float
            Dynamically determined end time of the experiment [s].
        u_next : numpy.ndarray
            Complete DAE state at the end of the experiment.
        cycle_solution : pybamm.Solution
            Full solution of the newly propagated experiment.
        """
        #starting_state = self.make_state(t, u)

        solution = self.sim.solve(
            starting_solution=starting_state,
            inputs=self.inputs,
            calc_esoh=False,
        )

        # starting_solution is represented by PyBaMM as an earlier
        # synthetic cycle. The final cycle is the newly computed one.
        cycle_solution = solution.cycles[-1]

        t_next, u_next = self.extract_state(cycle_solution)

        return t_next, u_next
    
    def propagate_with_solution(self, starting_state):
        """
        Propagate one complete experiment from (t, u).

        Parameters
        ----------
        t : float
            Starting numerical time [s].
        u : array-like
            Starting complete DAE state.

        Returns
        -------
        t_next : float
            Dynamically determined end time of the experiment [s].
        u_next : numpy.ndarray
            Complete DAE state at the end of the experiment.
        cycle_solution : pybamm.Solution
            Full solution of the newly propagated experiment.
        """
        #starting_state = self.make_state(t, u)

        solution = self.sim.solve(
            starting_solution=starting_state,
            inputs=self.inputs,
            calc_esoh=False,
        )

        # starting_solution is represented by PyBaMM as an earlier
        # synthetic cycle. The final cycle is the newly computed one.
        cycle_solution = solution.cycles[-1]

        t_next, u_next = self.extract_state(cycle_solution)

        return t_next, u_next, cycle_solution